name: "Feature Test"
description: "Create an unmanaged scratch org and run Apex tests"
inputs:
  dev-hub-auth-url:
    type: string
    required: True
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Run CumulusCI Flow
      uses: cumulusci-actions/execute-cumulusci-flow@main
      with:
        dev-hub-auth-url: ${{ inputs.dev-hub-auth-url }}
        org-name: feature
        flow-name: ci_feature
